---
title: "StrainCascade software licenses"
---

# Software license for StrainCascade

```         
MIT No Attribution License

Copyright (c) 2024-2025, University of Bern, Department for BioMedical Research, Sebastian Bruno Ulrich JORDI

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```

# Software licenses for third-party tools used in StrainCascade

> **Disclaimer**: The information provided here is for general guidance only. We do not guarantee the correctness or completeness of the license details listed. The authors and maintainers of StrainCascade are not liable for any discrepancies or legal issues that may arise from using the software shipped with containers. Users are strongly encouraged to verify the licenses of the software tools themselves to ensure compliance with their intended use.

------------------------------------------------------------------------

### Canu Assembly

-   **Tool Name:** Canu

-   **StrainCascade module:** SC1 and SC4

-   **StrainCascade script:** StrainCascade_Canu_correct_trim.sh and StrainCascade_Canu_assembly.sh

-   **License:** GNU GPL v2, BSD-3-Clause, Public Domain Notice (for U.S. Government work), Pacific Biosciences License

-   **Tool URL:** [Canu](https://github.com/marbl/canu)

-   **Information added:** October 03, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/canu_license.qmd" >}}

</details>

</details>

### LJA Assembly

-   **Main tool:** La Jolla Assembler

-   **StrainCascade module:** SC2

-   **StrainCascade script:** StrainCascade_LJA_assembly.sh

-   **License:** BSD-3-Clause

-   **Tool URL:** [LJA](https://github.com/AntonBankevich/LJA)

-   **Information added:** August 18, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/lja_license.qmd" >}}

</details>

### SPAdes Assembly

-   **Main tool:** SPAdes

-   **StrainCascade module:** SC3

-   **StrainCascade script:** StrainCascade_SPAdes_assembly.sh

-   **License:** GNU GPL v2

-   **Tool URL:** [SPAdes](https://github.com/ablab/spades)

-   **Information added:** August 18, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/spades_license.qmd" >}}

</details>

### Flye Assembly

-   **Tool Name:** Flye

-   **StrainCascade module:** SC5

-   **StrainCascade script:** StrainCascade_Flye_assembly.sh

-   **License:** BSD-3-Clause

-   **Tool URL:** [Flye](https://github.com/mikolmogorov/Flye)

-   **Information added:** October 13, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/flye_license.qmd" >}}

</details>

### QUAST assembly assessment

-   **Tool Name:** QUAST

-   **StrainCascade module:** SC6, SC8 and SC10

-   **StrainCascade script:** StrainCascade_assembly_evaluation1.sh, StrainCascade_assembly_evaluation2.sh and StrainCascade_assembly_evaluation3.sh

-   **License:** GNU GPL v2

-   **Tool URL:** [QUAST](https://github.com/ablab/quast)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/quast_license.qmd" >}}

</details>

### MAC2.0 Assembly Merging

-   **Tool Name:** MAC2.0

-   **StrainCascade module:** SC7

-   **StrainCascade script:** StrainCascade_MAC2_assembly_merging.sh

-   **License:** No license information is available to the best of our knowledge. Users are responsible for verifying the accuracy and appropriateness of any license information before use.

-   **Tool URL:** [MAC2.0](https://github.com/bioinfomaticsCSU/MAC)

-   **Information added:** October 13, 2024

### Circlator Circularisation

-   **Tool Name:** Circlator

-   **StrainCascade module:** SC9

-   **StrainCascade script:** StrainCascade_Circlator_circularisation.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [Circlator](https://github.com/mikolmogorov/Flye)

-   **Information added:** October 14, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/circlator_license.qmd" >}}

</details>

### Arrow polishing

-   **Tool Name:** arrow

-   **StrainCascade module:** SC11

-   **StrainCascade script:** StrainCascade_arrow_medaka_polishing.sh

-   **License:** BSD-3-Clause-Clear

-   **Tool URL:** [bioconda genomicconsensus](https://anaconda.org/bioconda/genomicconsensus)

-   **Tool URL:** [git pbbioconda](https://github.com/PacificBiosciences/pbbioconda)

-   **Information added:** October 14, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/arrow_conda_genomicconsensus_license.qmd" >}}

</details>

### Medaka polishing

-   **Tool Name:** medaka

-   **StrainCascade module:** SC11

-   **StrainCascade script:** StrainCascade_arrow_medaka_polishing.sh

-   **License:** Oxford Nanopore Technologies PLC. Public License Version 1.0 / MPL-2.0

-   **Tool URL:** [Bioconda medaka](https://anaconda.org/bioconda/medaka)

-   **Tool URL:** [GitHub medaka](https://github.com/nanoporetech/medaka)

-   **Information added:** October 14, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/medaka_conda_genomicconsensus_license.qmd" >}}

</details>

### NGMLR coverage assessment

-   **Tool Name:** NGMLR

-   **StrainCascade module:** SC12

-   **StrainCascade script:** StrainCascade_NGMLR_BBMap_coverage.sh

-   **License:** MIT

-   **Tool URL:** [NGMLR](https://github.com/philres/ngmlr)

-   **Information added:** October 17, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/ngmlr_license.qmd" >}}

</details>

### BBMap coverage assessment

-   **Tool Name:** BBMap

-   **StrainCascade module:** SC12

-   **StrainCascade script:** StrainCascade_NGMLR_BBMap_coverage.sh

-   **License:** BSD 3-Clause-like

-   **Tool URL:** [BBMap](https://sourceforge.net/projects/bbmap/)

-   **Information added:** October 17, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/bbmap_license.qmd" >}}

</details>

### CheckM2 QC

-   **Tool Name:** CheckM2

-   **StrainCascade module:** SC13

-   **StrainCascade script:** StrainCascade_CheckM2_QC.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [CheckM2](https://github.com/chklovski/CheckM2)

-   **Information added:** October 17, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/checkm2_license.qmd" >}}

</details>

### GTDB-Tk taxonomy

-   **Tool Name:** GTDB-Tk

-   **StrainCascade module:** SC14 and SC15

-   **StrainCascade script:** StrainCascade_GTDB-Tk_taxonomy.sh and StrainCascade_GTDB-Tk_de_novo_tree.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [GTDB](https://gtdb.ecogenomic.org/)

-   **Tool URL:** [GTDB-Tk](https://github.com/Ecogenomics/GTDBTk)

-   **Information added:** October 24, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/gtdbtk_license.qmd" >}}

</details>

### Bakta annotation

-   **Tool Name:** Bakta

-   **StrainCascade module:** SC16

-   **StrainCascade script:** StrainCascade_Bakta_annotation.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [Bakta](https://github.com/oschwengers/bakta?tab=readme-ov-file)

-   **Information added:** October 24, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/bakta_license.qmd" >}}

</details>

### Prokka annotation

-   **Tool Name:** Prokka

-   **StrainCascade module:** SC17

-   **StrainCascade script:** StrainCascade_Prokka_annotation.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [Prokka](https://github.com/tseemann/prokka)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/prokka_license.qmd" >}}

</details>

### MicrobeAnnotator annotation

-   **Tool Name:** MicrobeAnnotator

-   **StrainCascade module:** SC18

-   **StrainCascade script:** StrainCascade_MicrobeAnnotator_annotation.sh

-   **License:** Artistic License 2.0

-   **Tool URL:** [MicrobeAnnotator](https://github.com/cruizperez/MicrobeAnnotator)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/microbeannotator_license.qmd" >}}

</details>

### PlasmidFinder plasmid identification

-   **Tool Name:** PlasmidFinder

-   **StrainCascade module:** SC19

-   **StrainCascade script:** StrainCascade_PlasmidFinder_identification.sh

-   **License:** Apache License 2.0

-   **Tool URL:** [PlasmidFinder](https://github.com/kcri-tz/plasmidfinder?tab=readme-ov-file)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/plasmidfinder_license.qmd" >}}

</details>

### AMRFinderPlus antimicrobial resistance identification

-   **Tool Name:** AMRFinderPlus

-   **StrainCascade module:** SC20

-   **StrainCascade script:** StrainCascade_AMRFinderPlus_antimicrobial_resistance_identification.sh

-   **License:** Public domain notice

-   **Tool URL:** [AMRFinderPlus](https://github.com/ncbi/amr?tab=License-1-ov-file)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/amrfinderplus_license.qmd" >}}

</details>

### ResFinder antimicrobial resistance identification

-   **Tool Name:** ResFinder

-   **StrainCascade module:** SC21

-   **StrainCascade script:** StrainCascade_ResFinder_antimicrobial_resistance_identification.sh

-   **License:** Apache License 2.0

-   **Tool URL:** [ResFinder](https://github.com/genomicepidemiology/resfinder)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/resfinder_license.qmd" >}}

</details>

### dbCAN3 CAZymes identification

-   **Tool Name:** dbCAN3

-   **StrainCascade module:** SC22

-   **StrainCascade script:** StrainCascade_dbCAN3_CAZymes_identification.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [dbCAN3](https://github.com/linnabrown/run_dbcan)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/dbcan3_license.qmd" >}}

</details>

### IslandPath genomic islands identification

-   **Tool Name:** IslandPath

-   **StrainCascade module:** SC23

-   **StrainCascade script:** StrainCascade_IslandPath_genomic_islands_identification.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [IslandPath](https://github.com/brinkmanlab/islandpath)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/islandpath_license.qmd" >}}

</details>

### VirSorter2 viral sequences identification

-   **Tool Name:** VirSorter2

-   **StrainCascade module:** SC24

-   **StrainCascade script:** StrainCascade_VirSorter2_phage_identification.sh

-   **License:** GNU GPL v2

-   **Tool URL:** [VirSorter2](https://github.com/jiarong/VirSorter2)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/virsorter2_license.qmd" >}}

</details>

### DeepVirFinder viral sequences identification

-   **Tool Name:** DeepVirFinder

-   **StrainCascade module:** SC25

-   **StrainCascade script:** StrainCascade_DeepVirFinder_phage_identification.sh

-   **License:** USC-RL v1

-   **Tool URL:** [DeepVirFinder](https://github.com/jessieren/DeepVirFinder)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/deepvirfinder_license.qmd" >}}

</details>

### CrisprCasFinder CRISPR-Cas system identification

-   **Tool Name:** CRISPRCasFinder

-   **StrainCascade module:** SC26

-   **StrainCascade script:** StrainCascade_CRISPRCasFinder_identification.sh

-   **License:** GNU GPL v3

-   **Tool URL:** [CRISPRCasFinder](https://github.com/dcouvin/CRISPRCasFinder)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/crisprcasfinder_license.qmd" >}}

</details>

### ISEScan insertion sequence (IS) elements identification

-   **Tool Name:** ISEScan

-   **StrainCascade module:** SC27

-   **StrainCascade script:** StrainCascade_ISEScan_IS_elements_identification.sh

-   **License:** Apache License 2.0

-   **Tool URL:** [ISEScan](https://github.com/xiezhq/ISEScan)

-   **Information added:** December 16, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/isescan_license.qmd" >}}

</details>